// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.zilosoft.quote-reply",
  "name": "Zilosoft Quote Reply",
  "description": "Reply to a specific Mattermost message or selected fragment with a visible quote preview.",
  "homepage_url": "https://github.com/zilosoft/mattermost-reply",
  "support_url": "https://github.com/zilosoft/mattermost-reply/issues",
  "release_notes_url": "https://github.com/ZILosoft/mattermost-reply/releases",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "1.0.0",
  "min_server_version": "6.2.1",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Настройки Zilosoft Quote Reply",
    "footer": "",
    "settings": [
      {
        "key": "QuoteButtonLabel",
        "display_name": "Подпись кнопки цитаты",
        "type": "text",
        "help_text": "Текст для кнопки/иконки цитаты рядом с сообщением.",
        "placeholder": "",
        "default": "Quote",
        "hosting": "",
        "secret": false
      },
      {
        "key": "SelectionButtonLabel",
        "display_name": "Подпись popup-кнопки по выделению",
        "type": "text",
        "help_text": "Текст кнопки, которая появляется при выделении фрагмента сообщения.",
        "placeholder": "",
        "default": "Quote",
        "hosting": "",
        "secret": false
      },
      {
        "key": "EnableSelectionPopup",
        "display_name": "Показывать popup по выделению",
        "type": "bool",
        "help_text": "Если включено, при выделении текста внутри сообщения будет появляться popup-кнопка цитаты.",
        "placeholder": "",
        "default": true,
        "hosting": "",
        "secret": false
      },
      {
        "key": "LinkQuotesToSource",
        "display_name": "Делать цитаты ссылками",
        "type": "bool",
        "help_text": "Если включено, текст цитаты после отправки станет ссылкой на исходное сообщение.",
        "placeholder": "",
        "default": true,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
